package auth

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestHashAndVerifyPassword(t *testing.T) {
	password := "my-secret-password-123"

	hash, err := HashPassword(password)
	require.NoError(t, err)
	assert.NotEmpty(t, hash)
	assert.True(t, VerifyPassword(password, hash))
	assert.False(t, VerifyPassword("wrong-password", hash))
}

func TestVerifyPassword_LaravelCompatible(t *testing.T) {
	// This is a real bcrypt hash generated by Laravel (cost 10)
	laravelHash := "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"
	plainPassword := "password"

	assert.True(t, VerifyPassword(plainPassword, laravelHash))
}
